version: '3'
services:
  postgres:
    image: postgres:12-alpine
    container_name: cocos-challenge-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - cocos_challenge_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
  cocosChallengeBackend:
    container_name: cocos-challenge-backend
    image: 'node:18.10'
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - ../:/app
    environment: # Agregamos las variables de entorno para la conexión PostgreSQL
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: >
      sh -c "npm run migrations:run && npm run start"
volumes:
  cocos_challenge_data:
